set -g default-terminal "xterm-256color"
set -as terminal-features "xterm-256color:RGB"

# vim-bindings in copy-mode
setw -g mode-keys vi

# optional: navigate using vim-bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
