set -g mouse on
set -g default-terminal "xterm-256color"
set -as terminal-features "xterm-256color:RGB"
set -g base-index 1 # Start window numbering at 1
setw -g pane-base-index 1 # Start pane numbering at 1

# vim-bindings in copy-mode
setw -g mode-keys vi

# optional: navigate using vim-bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ---
# --- Cross-Platform Clipboard Support ---
# ---
# Requirements:
# MacOS: pbcopy (native)
# Debian (X11): xclip
# Debian (Wayland): wl-clipboard
# Arch (X11): xclip
# Arch (Wayland): wl-clipboard

# Start selection with 'v' and visual block toggle with 'C-v' (like Vim)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V   send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Use system clipboard depending
if-shell "uname | grep -q Darwin" {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
}

if-shell "uname | grep -q Linux" {
if-shell '[ -n "$WAYLAND_DISPLAY" ]' {
        bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
        bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
    } {
        bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
        bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
    }
  }

# Optional: Paste back from system clipboard with Prefix + p
if-shell "uname | grep -q Darwin" {
    bind-key p run-shell "pbpaste | tmux load-buffer - && tmux paste-buffer"
}
if-shell "uname | grep -q Linux" {
    if-shell '[ -n "$WAYLAND_DISPLAY" ]' {
        bind-key p run-shell "wl-paste | tmux load-buffer - && tmux paste-buffer"
    } {
        bind-key p run-shell "xclip -out -selection clipboard | tmux load-buffer - && tmux paste-buffer"
    }
}
